name: passport-network-caliper
version: "2.0.0"
caliper:
  blockchain: fabric

channels:
  - channelName: CHANNEL_NAME_PLACEHOLDER
    contracts:
      - id: passport-contract

organizations:
  - mspid: ORG_MSP_PLACEHOLDER
    connectionProfile:
      path: ORG_CONNPROFILE_PLACEHOLDER
      discover: true
    identities:
      certificates:
        - name: admin
          clientPrivateKey:
            path: ORG_KEYSTORE_PLACEHOLDER
          clientSignedCert:
            path: ORG_SIGNCERT_PLACEHOLDER
