services:
  peer0.manufacturer.battery.com:
    environment:
      - CORE_PEER_LIMITS_CONCURRENCY_ENDORSERSERVICE=${BENCHMARK_PEER_ENDORSER_CONCURRENCY:-5000}
      - CORE_PEER_LIMITS_CONCURRENCY_DELIVERSERVICE=${BENCHMARK_PEER_DELIVER_CONCURRENCY:-5000}
      - CORE_PEER_LIMITS_CONCURRENCY_GATEWAYSERVICE=${BENCHMARK_PEER_GATEWAY_CONCURRENCY:-2000}

  peer0.evmanufacturer.battery.com:
    environment:
      - CORE_PEER_LIMITS_CONCURRENCY_ENDORSERSERVICE=${BENCHMARK_PEER_ENDORSER_CONCURRENCY:-5000}
      - CORE_PEER_LIMITS_CONCURRENCY_DELIVERSERVICE=${BENCHMARK_PEER_DELIVER_CONCURRENCY:-5000}
      - CORE_PEER_LIMITS_CONCURRENCY_GATEWAYSERVICE=${BENCHMARK_PEER_GATEWAY_CONCURRENCY:-2000}

  peer0.service.battery.com:
    environment:
      - CORE_PEER_LIMITS_CONCURRENCY_ENDORSERSERVICE=${BENCHMARK_PEER_ENDORSER_CONCURRENCY:-5000}
      - CORE_PEER_LIMITS_CONCURRENCY_DELIVERSERVICE=${BENCHMARK_PEER_DELIVER_CONCURRENCY:-5000}
      - CORE_PEER_LIMITS_CONCURRENCY_GATEWAYSERVICE=${BENCHMARK_PEER_GATEWAY_CONCURRENCY:-2000}

  peer0.regulator.battery.com:
    environment:
      - CORE_PEER_LIMITS_CONCURRENCY_ENDORSERSERVICE=${BENCHMARK_PEER_ENDORSER_CONCURRENCY:-5000}
      - CORE_PEER_LIMITS_CONCURRENCY_DELIVERSERVICE=${BENCHMARK_PEER_DELIVER_CONCURRENCY:-5000}
      - CORE_PEER_LIMITS_CONCURRENCY_GATEWAYSERVICE=${BENCHMARK_PEER_GATEWAY_CONCURRENCY:-2000}
