#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${ROOT_DIR}"

PERFORMANCE_GOAL_SLUG="${PERFORMANCE_GOAL_SLUG:-chaincode-hotpath-write200}"
BASE="${EVIDENCE_BASE:-.omx/evidence/blockchain/${PERFORMANCE_GOAL_SLUG}/official-$(date +%Y%m%dT%H%M%S%Z)}"
TS="${RUN_TS:-$(date +%Y%m%dT%H%M%S%Z)}"
RUN_ID="${RUN_ID:-official-write200-reconcile-${TS}}"
CHANNEL_NAME="${CHANNEL_NAME:-passportof$(date +%m%d%H%M%S)}"
EVIDENCE_ROOT="${EVIDENCE_ROOT:-${BASE}/${RUN_ID}}"
MIN_DOCKER_CPUS="${MIN_DOCKER_CPUS:-12}"
MIN_DOCKER_MEMORY_GIB="${MIN_DOCKER_MEMORY_GIB:-24}"
ALLOW_UNDERPOWERED="${ALLOW_UNDERPOWERED:-false}"
RUN_RC=0
VERIFY_RC=0
VERIFY_JSON="${EVIDENCE_ROOT}/official-write-verify.json"
VERIFY_ENV="${EVIDENCE_ROOT}/official-write-verify.env"
VERIFY_LOG="${EVIDENCE_ROOT}/official-write-verify.log"
STATIC_RC=0
STATIC_LOG="${EVIDENCE_ROOT}/static-checks.log"
GOAL_WRITE_ENV="${EVIDENCE_ROOT}/performance-goal-write-result.env"

mkdir -p "${EVIDENCE_ROOT}"

HOST_READINESS_JSON="${EVIDENCE_ROOT}/host-readiness.json"
set +e
MIN_DOCKER_CPUS="${MIN_DOCKER_CPUS}" \
MIN_DOCKER_MEMORY_GIB="${MIN_DOCKER_MEMORY_GIB}" \
ALLOW_UNDERPOWERED="${ALLOW_UNDERPOWERED}" \
  scripts/check-benchmark-host-readiness.sh --output "${HOST_READINESS_JSON}" \
  > "${EVIDENCE_ROOT}/host-readiness.log" 2>&1
readiness_rc=$?
set -e

if (( readiness_rc != 0 )); then
  {
    echo "RUN_ID=${RUN_ID}"
    echo "CHANNEL_NAME=${CHANNEL_NAME}"
    echo "EVIDENCE_ROOT=${EVIDENCE_ROOT}"
    echo "STATUS=blocked_underpowered_host"
    echo "HOST_READINESS_JSON=${HOST_READINESS_JSON}"
    echo "END=$(date -Is)"
  } | tee "${EVIDENCE_ROOT}/final-status.env"
  echo "Blocked: Docker host does not meet benchmark readiness floor; see ${HOST_READINESS_JSON}" >&2
  exit "${readiness_rc}"
fi

if [[ "${CALIPER_RECORD_AUTO_ID:-true}" =~ ^([Tt][Rr][Uu][Ee]|1|yes|YES|on|ON)$ ]]; then
  OFFICIAL_WRITE_CONTRACT_FUNCTION="RecordBMUDataAutoID"
else
  OFFICIAL_WRITE_CONTRACT_FUNCTION="RecordBMUData"
fi

{
  echo "RUN_ID=${RUN_ID}"
  echo "CHANNEL_NAME=${CHANNEL_NAME}"
  echo "EVIDENCE_ROOT=${EVIDENCE_ROOT}"
  echo "START=$(date -Is)"
  echo "MIN_DOCKER_CPUS=${MIN_DOCKER_CPUS}"
  echo "MIN_DOCKER_MEMORY_GIB=${MIN_DOCKER_MEMORY_GIB}"
  echo "ALLOW_UNDERPOWERED=${ALLOW_UNDERPOWERED}"
  echo "CALIPER_EXEC_MODE=${CALIPER_EXEC_MODE:-host}"
  echo "CALIPER_ENDPOINT_MODE=${CALIPER_ENDPOINT_MODE:-host}"
  echo "CALIPER_DOCKER_NETWORK=${CALIPER_DOCKER_NETWORK:-passport_net}"
  echo "CALIPER_RECORD_AUTO_ID=${CALIPER_RECORD_AUTO_ID:-true}"
  echo "CALIPER_WRITE_TX_NUMBER=${CALIPER_WRITE_TX_NUMBER:-10000}"
  echo "CALIPER_WRITE_TARGET_TPS=${CALIPER_WRITE_TARGET_TPS:-400}"
  echo "CALIPER_WRITE_ROUND_LABEL=write-bmu-data"
  echo "CALIPER_WRITE_WORKLOAD_MODULE=workloads/recordBMUData.js"
  echo "CALIPER_WRITE_CONTRACT_FUNCTION=${OFFICIAL_WRITE_CONTRACT_FUNCTION}"
  echo "COLLECT_HOST_RESOURCE_STATS=${COLLECT_HOST_RESOURCE_STATS:-true}"
} | tee "${EVIDENCE_ROOT}/launch.env"

CLEAN_DIR="${BASE}/cleanup-after-${RUN_ID}-$(date +%Y%m%dT%H%M%S%Z)"
cleanup() {
  mkdir -p "${CLEAN_DIR}"
  DRY_RUN=false \
  CONFIRM_BENCHMARK_CLEANUP=benchmark-only \
  EVIDENCE_DIR="${CLEAN_DIR}" \
    scripts/cleanup-benchmark-fabric-artifacts.sh > "${CLEAN_DIR}/cleanup.log" 2>&1 || true
  {
    echo "DIR=${EVIDENCE_ROOT}"
    echo "CLEAN_DIR=${CLEAN_DIR}"
    echo "RUN_RC=${RUN_RC}"
    echo "END=$(date -Is)"
  } > "${EVIDENCE_ROOT}/final-status.env"
}
trap cleanup EXIT

run_static_checks() {
  set +e
  {
    echo "# static checks $(date -Is)"
    bash -n scripts/run-official-write200-audit.sh
    bash -n scripts/verify-official-write200-evidence.sh
    bash -n scripts/blockchain-tps-reproducibility.sh
    bash -n scripts/identify-benchmark-ledger-validity.sh
    bash -n scripts/wait-peer-heights-equal.sh
    bash -n scripts/cleanup-benchmark-fabric-artifacts.sh
    node -c scripts/reconcile-benchmark-state.js
    node -c caliper-workspace/workloads/recordBMUData.js
    (cd chaincode/passport-contract && go test ./...)
  } > "${STATIC_LOG}" 2>&1
  STATIC_RC=$?
  set -e
}

write_goal_result_env() {
  {
    echo "# Generated by scripts/run-official-write200-audit.sh at $(date -Is)"
    if [[ -f "${EVIDENCE_ROOT}/summary.env" ]]; then
      cat "${EVIDENCE_ROOT}/summary.env"
    fi
    echo "CLEANUP_VERIFY_LOG=${CLEAN_DIR}/cleanup.log"
    echo "STATIC_CHECKS_LOG=${STATIC_LOG}"
    if (( STATIC_RC == 0 )); then
      echo "STATIC_CHECKS_PASS=true"
    else
      echo "STATIC_CHECKS_PASS=false"
    fi
    echo "OFFICIAL_WRITE_VERIFY_JSON=${VERIFY_JSON}"
    echo "OFFICIAL_WRITE_VERIFY_ENV=${VERIFY_ENV}"
    echo "OFFICIAL_WRITE_VERIFY_LOG=${VERIFY_LOG}"
    echo "OFFICIAL_WRITE_VERIFY_RC=${VERIFY_RC}"
    # VERIFY_ENV carries OFFICIAL_WRITE_HOST_READINESS_STATUS and
    # OFFICIAL_WRITE_ALLOW_UNDERPOWERED into performance-goal latest-results.env.
    if [[ -f "${VERIFY_ENV}" ]]; then
      cat "${VERIFY_ENV}"
    fi
    if (( VERIFY_RC == 0 )); then
      echo "CURRENT_WRITE_GATE_STATUS=pass"
    else
      echo "CURRENT_WRITE_GATE_STATUS=validation_failed"
    fi
  } > "${GOAL_WRITE_ENV}"

  if [[ "${UPDATE_PERFORMANCE_GOAL_RESULTS:-false}" == "true" ]]; then
    local goal_env="${PERFORMANCE_GOAL_RESULTS_FILE:-.omx/goals/performance/${PERFORMANCE_GOAL_SLUG}/latest-results.env}"
    mkdir -p "$(dirname "${goal_env}")"
    {
      echo
      echo "# Official write result from ${EVIDENCE_ROOT}"
      cat "${GOAL_WRITE_ENV}"
    } >> "${goal_env}"
  fi
}

set +e
env \
  RUN_ID="${RUN_ID}" \
  CHANNEL_NAME="${CHANNEL_NAME}" \
  EVIDENCE_ROOT="${EVIDENCE_ROOT}" \
  BENCHMARK_CHANNEL_PROFILE="${BENCHMARK_CHANNEL_PROFILE:-PassportBenchmarkChannel}" \
  BENCHMARK_CHANNEL_ORGS="${BENCHMARK_CHANNEL_ORGS:-1,2,3,4}" \
  BENCHMARK_CC_INSTALL_ORGS="${BENCHMARK_CC_INSTALL_ORGS:-1,2,3,4}" \
  BENCHMARK_CC_VERSION="${BENCHMARK_CC_VERSION:-1.0-${TS}}" \
  BENCHMARK_CC_SEQUENCE="${BENCHMARK_CC_SEQUENCE:-1}" \
  BENCHMARK_PEER_CONCURRENCY="${BENCHMARK_PEER_CONCURRENCY:-true}" \
  BENCHMARK_PEER_ENDORSER_CONCURRENCY="${BENCHMARK_PEER_ENDORSER_CONCURRENCY:-5000}" \
  BENCHMARK_PEER_DELIVER_CONCURRENCY="${BENCHMARK_PEER_DELIVER_CONCURRENCY:-5000}" \
  BENCHMARK_PEER_GATEWAY_CONCURRENCY="${BENCHMARK_PEER_GATEWAY_CONCURRENCY:-2000}" \
  ORG="${ORG:-evmanufacturer}" \
  PREPARE_ORG="${PREPARE_ORG:-manufacturer}" \
  REPEAT_COUNT="${REPEAT_COUNT:-10}" \
  CALIPER_WRITE_TX_NUMBER="${CALIPER_WRITE_TX_NUMBER:-10000}" \
  CALIPER_WRITE_TARGET_TPS="${CALIPER_WRITE_TARGET_TPS:-400}" \
  CALIPER_SKIP_READ_ROUND=true \
  CALIPER_RECORD_AUTO_ID="${CALIPER_RECORD_AUTO_ID:-true}" \
  NUM_PASSPORTS="${NUM_PASSPORTS:-10000}" \
  BMU_RECORD_KEYS="${BMU_RECORD_KEYS:-10000}" \
  PREPARED_BMU_RECORD_KEYS="${PREPARED_BMU_RECORD_KEYS:-10000}" \
  RUN_BMU_RECORD_KEYS="${RUN_BMU_RECORD_KEYS:-10000}" \
  CALIPER_WORKERS="${CALIPER_WORKERS:-4}" \
  CALIPER_FABRIC_GATEWAY_EVENTSTRATEGY="${CALIPER_FABRIC_GATEWAY_EVENTSTRATEGY:-msp_any}" \
  CALIPER_OBSERVER_INTERNAL_INTERVAL="${CALIPER_OBSERVER_INTERNAL_INTERVAL:-10000}" \
  CALIPER_FABRIC_TIMEOUT_INVOKEORQUERY="${CALIPER_FABRIC_TIMEOUT_INVOKEORQUERY:-180}" \
  CALIPER_VERIFY_PREPARED_EACH_REPEAT="${CALIPER_VERIFY_PREPARED_EACH_REPEAT:-false}" \
  COLLECT_DOCKER_STATS="${COLLECT_DOCKER_STATS:-true}" \
  COLLECT_HOST_RESOURCE_STATS="${COLLECT_HOST_RESOURCE_STATS:-true}" \
  CALIPER_TXMAP_DIR="${EVIDENCE_ROOT}/txmap" \
  RECONCILE_AFTER_RUNS=true \
  RECONCILE_REQUIRED=true \
  IDENTIFY_LEDGER_VALIDITY_AFTER_RUNS="${IDENTIFY_LEDGER_VALIDITY_AFTER_RUNS:-true}" \
  IDENTIFY_LEDGER_VALIDITY_REQUIRED="${IDENTIFY_LEDGER_VALIDITY_REQUIRED:-false}" \
  WAIT_FOR_PEER_HEIGHTS_EQUAL="${WAIT_FOR_PEER_HEIGHTS_EQUAL:-true}" \
  WAIT_FOR_PEER_HEIGHTS_REQUIRED="${WAIT_FOR_PEER_HEIGHTS_REQUIRED:-true}" \
  PEER_HEIGHTS_TIMEOUT="${PEER_HEIGHTS_TIMEOUT:-300}" \
  PEER_HEIGHTS_INTERVAL="${PEER_HEIGHTS_INTERVAL:-5}" \
  WAIT_FOR_DOCKER_IDLE=true \
  WAIT_FOR_COUCHDB_ACTIVE_TASKS=true \
  DOCKER_IDLE_MAX_CPU=15 \
  DOCKER_IDLE_CONSECUTIVE=2 \
  DOCKER_IDLE_TIMEOUT=600 \
  DOCKER_IDLE_INTERVAL=10 \
  scripts/blockchain-tps-reproducibility.sh 2>&1 | tee "${EVIDENCE_ROOT}/run.log"
RUN_RC=${PIPESTATUS[0]}
set -e

cleanup
trap - EXIT

run_static_checks

set +e
scripts/verify-official-write200-evidence.sh \
  --evidence-dir "${EVIDENCE_ROOT}" \
  --output "${VERIFY_JSON}" \
  --env-output "${VERIFY_ENV}" \
  > "${VERIFY_LOG}" 2>&1
VERIFY_RC=$?
set -e

write_goal_result_env

{
  echo "VERIFY_JSON=${VERIFY_JSON}"
  echo "VERIFY_ENV=${VERIFY_ENV}"
  echo "VERIFY_LOG=${VERIFY_LOG}"
  echo "VERIFY_RC=${VERIFY_RC}"
  echo "STATIC_LOG=${STATIC_LOG}"
  echo "STATIC_RC=${STATIC_RC}"
  echo "GOAL_WRITE_ENV=${GOAL_WRITE_ENV}"
} >> "${EVIDENCE_ROOT}/final-status.env"

if (( RUN_RC != 0 )); then
  exit "${RUN_RC}"
fi
if (( STATIC_RC != 0 )); then
  exit "${STATIC_RC}"
fi
exit "${VERIFY_RC}"
