/*==================================================================================================
*   Project              : RTD AUTOSAR 4.7
*   Platform             : CORTEXM
*   Peripheral           : FLEXCAN
*   Dependencies         : 
*
*   Autosar Version      : 4.7.0
*   Autosar Revision     : ASR_REL_4_7_REV_0000
*   Autosar Conf.Variant :
*   SW Version           : 3.0.0
*   Build Version        : S32K1_RTD_3_0_0_D2503_ASR_REL_4_7_REV_0000_20250307
*
*   Copyright 2020-2025 NXP
*
*   NXP Confidential and Proprietary. This software is owned or controlled by NXP and may only be
*   used strictly in accordance with the applicable license terms. By expressly
*   accepting such terms or by downloading, installing, activating and/or otherwise
*   using the software, you are agreeing that you have read, and that you agree to
*   comply with and are bound by, such license terms. If you do not agree to be
*   bound by the applicable license terms, then you may not retain, install,
*   activate or otherwise use the software.
==================================================================================================*/
/***********************************************************************************************************************
 * This file was generated by the S32 Configuration Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Configuration Tools is used to update this file.
 **********************************************************************************************************************/

/**
*   @file FlexCAN_Ip_Sa_PBcfg.c
*
*   @addtogroup FlexCAN
*   @{
*/

#ifdef __cplusplus
extern "C"{
#endif

/*==================================================================================================
*                                        INCLUDE FILES
* 1) system and project includes
* 2) needed interfaces from external units
* 3) internal and external interfaces from this unit
==================================================================================================*/
#include "FlexCAN_Ip_Types.h"
#if (FLEXCAN_IP_FEATURE_HAS_DMA_ENABLE == STD_ON)
    #include "Dma_Ip.h"
#endif
/*==================================================================================================
*                              SOURCE FILE VERSION INFORMATION
==================================================================================================*/
#define FLEXCAN_IP_SA_VENDOR_ID_PBCFG_C                     43
#define FLEXCAN_IP_SA_AR_RELEASE_MAJOR_VERSION_PBCFG_C      4
#define FLEXCAN_IP_SA_AR_RELEASE_MINOR_VERSION_PBCFG_C      7
#define FLEXCAN_IP_SA_AR_RELEASE_REVISION_VERSION_PBCFG_C   0
#define FLEXCAN_IP_SA_SW_MAJOR_VERSION_PBCFG_C              3
#define FLEXCAN_IP_SA_SW_MINOR_VERSION_PBCFG_C              0
#define FLEXCAN_IP_SA_SW_PATCH_VERSION_PBCFG_C              0
/*==================================================================================================
*                                     FILE VERSION CHECKS
==================================================================================================*/
/* Checks against current file and FlexCAN_Ip_Types.h */
#if (FLEXCAN_IP_SA_VENDOR_ID_PBCFG_C != FLEXCAN_IP_TYPES_VENDOR_ID_H)
    #error "FlexCAN_Ip_Sa_PBcfg.c and FlexCAN_Ip_Types.h have different vendor ids"
#endif
#if ((FLEXCAN_IP_SA_AR_RELEASE_MAJOR_VERSION_PBCFG_C     != FLEXCAN_IP_TYPES_AR_RELEASE_MAJOR_VERSION_H) || \
     (FLEXCAN_IP_SA_AR_RELEASE_MINOR_VERSION_PBCFG_C     != FLEXCAN_IP_TYPES_AR_RELEASE_MINOR_VERSION_H) || \
     (FLEXCAN_IP_SA_AR_RELEASE_REVISION_VERSION_PBCFG_C  != FLEXCAN_IP_TYPES_AR_RELEASE_REVISION_VERSION_H) \
    )
    #error "AutoSar Version Numbers of FlexCAN_Ip_Sa_PBcfg.c and FlexCAN_Ip_Types.h are different"
#endif
#if ((FLEXCAN_IP_SA_SW_MAJOR_VERSION_PBCFG_C != FLEXCAN_IP_TYPES_SW_MAJOR_VERSION_H) || \
     (FLEXCAN_IP_SA_SW_MINOR_VERSION_PBCFG_C != FLEXCAN_IP_TYPES_SW_MINOR_VERSION_H) || \
     (FLEXCAN_IP_SA_SW_PATCH_VERSION_PBCFG_C != FLEXCAN_IP_TYPES_SW_PATCH_VERSION_H) \
    )
    #error "Software Version Numbers of FlexCAN_Ip_Sa_PBcfg.c and FlexCAN_Ip_Types.h are different"
#endif

#ifndef DISABLE_MCAL_INTERMODULE_ASR_CHECK
    /* Checks against current file and Dma_Ip.h */
    #if (FLEXCAN_IP_FEATURE_HAS_DMA_ENABLE == STD_ON)
        #if ((FLEXCAN_IP_SA_AR_RELEASE_MAJOR_VERSION_PBCFG_C != DMA_IP_AR_RELEASE_MAJOR_VERSION) || \
             (FLEXCAN_IP_SA_AR_RELEASE_MINOR_VERSION_PBCFG_C != DMA_IP_AR_RELEASE_MINOR_VERSION) \
            )
            #error "AutoSar Version Numbers of FlexCAN_Ip_Sa_PBcfg.c and Dma_Ip.h are different"
        #endif
    #endif
#endif
/*==================================================================================================
*                                   GLOBAL FUNCTION PROTOTYPES
==================================================================================================*/
#define CAN_43_FLEXCAN_START_SEC_CODE
#include "Can_43_FLEXCAN_MemMap.h"

extern void FlexCAN_CallbackFunction(uint8 instance, Flexcan_Ip_EventType eventType,
                uint32 buffIdx, const Flexcan_Ip_StateType * flexcanState);
#define CAN_43_FLEXCAN_STOP_SEC_CODE
#include "Can_43_FLEXCAN_MemMap.h"
/*==================================================================================================
*                                GLOBAL VARIABLE DECLARATIONS
==================================================================================================*/
#define CAN_43_FLEXCAN_START_SEC_VAR_CLEARED_UNSPECIFIED
#include "Can_43_FLEXCAN_MemMap.h"
/* FlexCAN State Structure used By driver
User should not modify this structure */
Flexcan_Ip_StateType FlexCAN_State0;
#define CAN_43_FLEXCAN_STOP_SEC_VAR_CLEARED_UNSPECIFIED
#include "Can_43_FLEXCAN_MemMap.h"
/*==================================================================================================
*                                      GLOBAL CONSTANTS
==================================================================================================*/
#define CAN_43_FLEXCAN_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "Can_43_FLEXCAN_MemMap.h"

const Flexcan_Ip_ConfigType FlexCAN_Config0  = {
    /* Number Of Message Buffer used .max_num_mb  */
    /* NOTE: With 64-byte payload, each MB = 72 bytes. S32K144 FlexCAN RAM = 512 bytes.
     * Max MBs = 512/72 = 7. Original value 12 causes BUFF_OUT_OF_RANGE. */
    (uint8)7,
    /*Can Hw filter count* .num_id_filters*- aici exista variatna sa generez toate filtrele si sa referentiezi tu in cod */
    FLEXCAN_RX_FIFO_ID_FILTERS_8,
    /* Legacy FIFO ENABLED .is_rx_fifo_needed*/
    (boolean)FALSE,
#if (FLEXCAN_IP_FEATURE_HAS_ENHANCED_RX_FIFO == STD_ON)
    /* The number of standard ID filter elements */
    0U,
    /* The number of extended ID filter elements */
    0U,
    /* The number of enhanced Rx FIFO watermark */
    0U,
    /* The Enhanced Rx FIFO feature is enabled or not. */
    (boolean)FALSE,
#endif
#if (FLEXCAN_IP_FEATURE_HAS_TS_ENABLE == STD_ON)
    /* TimeStamp Structure Configuration */
    {
        /* timeStampSurce Timer Source */
        FLEXCAN_CAN_CLK_TIMESTAMP_SRC
    },
#endif /* (FLEXCAN_IP_FEATURE_HAS_TS_ENABLE == STD_ON) */
    FLEXCAN_NORMAL_MODE,
#if (FLEXCAN_IP_FEATURE_HAS_MEM_ERR_DET == STD_ON)
#if (FLEXCAN_IP_FEATURE_MEM_ERR_DET_ENABLED == STD_ON)
    /* Memory error response .flexcanModeErrResponse */
    FLEXCAN_NORMAL_MODE,
#endif
#endif
     /*ctrlOptions*/
    (uint32)(FLEXCAN_IP_ISO_U32 | \
    \
    \
    \
    0U),
     /* Can FD RamBlock specified *//*.payload*/
    {
      FLEXCAN_PAYLOAD_SIZE_64
    },
        /*Can FD enabled .fd_enable*/
        (boolean)TRUE,
#if (FLEXCAN_IP_FEATURE_HAS_PE_CLKSRC_SELECT == STD_ON)
        /* Can PE clock selected .is_pe_clock */
        (boolean)TRUE,
#endif
        /*Enhance CBT support . extCbtEnable*/
        (boolean)FALSE,
        /*BRS for FD .bitRateSwitch*/
        (boolean)TRUE,
        /*values for normal baudrate .bitrate - 500kbps @ 48MHz PE clock
         * HW adds +1 to each config value!
         * Config: PropSeg=6, PSeg1=4, PSeg2=2, PreDiv=5, RJW=2
         * Actual: PropSeg=7, PSeg1=5, PSeg2=3, PreDiv=6, RJW=3
         * BitTime = 1+7+5+3 = 16 tq, SP = 13/16 = 81.25%
         * 48MHz / (6 * 16) = 500kbps */
        {   /* Prop Seg */
            (6U),
            /* Phase Seg 1 */
            (4U),
            /* Phase Seg 2*/
            (2U),
            /* Pre Divider */
            (5U),
            /* Resync jump width */
            (2U)
        },
            /*values for FD baudrate .bitrate - 2Mbps @ 48MHz PE clock
             * FDCBT +1 규칙: FPROPSEG은 그대로, FPSEG1/FPSEG2/FPRESDIV/FRJW만 +1
             * Formula: BT = 1 + FPROPSEG + (FPSEG1+1) + (FPSEG2+1)
             * Config: FPROPSEG=4, FPSEG1=4, FPSEG2=1, FPRESDIV=1, FRJW=1
             * Actual: PropSeg=4, PSeg1=5, PSeg2=2, PreDiv=2, RJW=2
             * BitTime = 1+4+5+2 = 12 tq, SP = (1+4+5)/12 = 83.3%
             * 48MHz / (2 * 12) = 2Mbps ✓ */
        {   /* Prop Seg */
            (4U),
            /* Phase Seg 1 */
            (4U),
            /* Phase Seg 2*/
            (1U),
            /* Pre Divider */
            (1U),
            /* Resync jump width */
            (1U)
        },
        /*transfer_type*/
        FLEXCAN_RXFIFO_USING_INTERRUPTS,
#if (FLEXCAN_IP_FEATURE_HAS_DMA_ENABLE == STD_ON)
     /* DMA channel number used for transfers. */
         0,
  #endif
    /* Controller Callback */
    &FlexCAN_CallbackFunction,
    /* Error Callback */
    NULL_PTR
    };
    
#define CAN_43_FLEXCAN_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "Can_43_FLEXCAN_MemMap.h"

#ifdef __cplusplus
}
#endif
/** @} */

