%% create_bms_simulink.m
%  Creates a Simulink model for BMS battery simulation with UDP output.
%  No Simulink toolboxes required (uses MATLAB Function block + Java UDP).
%
%  Usage:
%    1. Run this script in MATLAB: create_bms_simulink
%    2. The model "BMS_Battery_Sim" will open
%    3. Click Run (or press Ctrl+T) to start simulation
%    4. Make sure dataProcess.py is running before starting
%
%  Data flow:
%    Simulink Model -> UDP:5005 -> dataProcess.py -> UART -> CMU -> CAN-FD -> BMU

function create_bms_simulink()
    modelName = 'BMS_Battery_Sim';

    % Close if already open
    if bdIsLoaded(modelName)
        close_system(modelName, 0);
    end

    % Create new model
    new_system(modelName);
    open_system(modelName);

    % Set simulation parameters
    set_param(modelName, 'StopTime', '600');           % 10 minutes
    set_param(modelName, 'FixedStep', '0.05');         % 50ms step
    set_param(modelName, 'Solver', 'FixedStepDiscrete');

    %% Add Clock block
    add_block('simulink/Sources/Clock', [modelName '/Clock']);
    set_param([modelName '/Clock'], 'Position', [50 150 80 170]);

    %% Add MATLAB Function block - Battery Model + UDP Send
    mfPath = [modelName '/BMS_Battery_UDP'];
    add_block('simulink/User-Defined Functions/MATLAB Function', mfPath);
    set_param(mfPath, 'Position', [200 120 400 200]);

    % Connect Clock to MATLAB Function
    add_line(modelName, 'Clock/1', 'BMS_Battery_UDP/1');

    %% Add Display blocks for monitoring
    % SOC Display
    add_block('simulink/Sinks/Display', [modelName '/SOC_pct']);
    set_param([modelName '/SOC_pct'], 'Position', [500 50 580 70]);
    add_line(modelName, 'BMS_Battery_UDP/1', 'SOC_pct/1');

    % Current Display
    add_block('simulink/Sinks/Display', [modelName '/Current_A']);
    set_param([modelName '/Current_A'], 'Position', [500 100 580 120]);
    add_line(modelName, 'BMS_Battery_UDP/2', 'Current_A/1');

    % Voltage Display
    add_block('simulink/Sinks/Display', [modelName '/Voltage_V']);
    set_param([modelName '/Voltage_V'], 'Position', [500 150 580 170]);
    add_line(modelName, 'BMS_Battery_UDP/3', 'Voltage_V/1');

    % Temperature Display
    add_block('simulink/Sinks/Display', [modelName '/Temp_C']);
    set_param([modelName '/Temp_C'], 'Position', [500 200 580 220]);
    add_line(modelName, 'BMS_Battery_UDP/4', 'Temp_C/1');

    % Cycles Display
    add_block('simulink/Sinks/Display', [modelName '/Cycles']);
    set_param([modelName '/Cycles'], 'Position', [500 250 580 270]);
    add_line(modelName, 'BMS_Battery_UDP/5', 'Cycles/1');

    %% Add Scope for plotting
    add_block('simulink/Sinks/Scope', [modelName '/Battery_Scope']);
    set_param([modelName '/Battery_Scope'], 'Position', [500 310 540 350]);
    set_param([modelName '/Battery_Scope'], 'NumInputPorts', '3');
    add_line(modelName, 'BMS_Battery_UDP/1', 'Battery_Scope/1');  % SOC
    add_line(modelName, 'BMS_Battery_UDP/2', 'Battery_Scope/2');  % Current
    add_line(modelName, 'BMS_Battery_UDP/3', 'Battery_Scope/3');  % Voltage

    %% Set MATLAB Function code
    % Get the MATLAB Function block handle
    sfRoot = sfroot;
    chart = sfRoot.find('-isa', 'Stateflow.EMChart', 'Path', mfPath);

    if ~isempty(chart)
        chart.Script = getBatteryUdpCode();
    end

    %% Save model
    savePath = fullfile(pwd, [modelName '.slx']);
    save_system(modelName, savePath);

    fprintf('\n========================================\n');
    fprintf('  Simulink model created: %s\n', modelName);
    fprintf('========================================\n');
    fprintf('\nSteps:\n');
    fprintf('  1. Start dataProcess.py:\n');
    fprintf('     python dataProcess.py --port COM5 --baud 9600\n');
    fprintf('  2. Click Run in Simulink (or Ctrl+T)\n');
    fprintf('  3. Watch the Scope and Display blocks\n');
    fprintf('  4. Check BMU serial output (COM4, 28800 baud)\n');
    fprintf('\nSimulation time: 600s (10 min)\n');
    fprintf('Sample time: 50ms\n');
    fprintf('========================================\n');
end

function code = getBatteryUdpCode()
    code = [...
        'function [soc_pct, current, voltage, temp_c, cycles] = BMS_Battery_UDP(t)' newline ...
        '%#codegen' newline ...
        '% BMS Battery Simulation with UDP output' newline ...
        '% Simulates Li-ion battery discharge/charge cycle' newline ...
        '% Sends 27 doubles (216 bytes) via UDP to dataProcess.py' newline ...
        '' newline ...
        'persistent udpSocket udpAddr soc cyc charging prev_t' newline ...
        '' newline ...
        'NUM_CELLS = 11;' newline ...
        'UDP_IP = ''127.0.0.1'';' newline ...
        'UDP_PORT = 5005;' newline ...
        'DT = 0.05;' newline ...
        '' newline ...
        'if isempty(soc)' newline ...
        '    soc = 0.95;' newline ...
        '    cyc = 0;' newline ...
        '    charging = false;' newline ...
        '    prev_t = -1;' newline ...
        '    import java.net.DatagramSocket' newline ...
        '    import java.net.DatagramPacket' newline ...
        '    import java.net.InetAddress' newline ...
        '    udpSocket = DatagramSocket();' newline ...
        '    udpAddr = InetAddress.getByName(UDP_IP);' newline ...
        'end' newline ...
        '' newline ...
        '% Avoid duplicate steps' newline ...
        'if t <= prev_t' newline ...
        '    soc_pct = soc * 100;' newline ...
        '    current = 0;' newline ...
        '    voltage = 0;' newline ...
        '    temp_c = 25;' newline ...
        '    cycles = cyc;' newline ...
        '    return;' newline ...
        'end' newline ...
        'prev_t = t;' newline ...
        '' newline ...
        '% Battery dynamics' newline ...
        'if ~charging' newline ...
        '    soc = soc - 0.001 * DT;' newline ...
        '    if soc <= 0.15' newline ...
        '        charging = true;' newline ...
        '        cyc = cyc + 1;' newline ...
        '    end' newline ...
        'else' newline ...
        '    soc = soc + 0.002 * DT;' newline ...
        '    if soc >= 0.95' newline ...
        '        charging = false;' newline ...
        '    end' newline ...
        'end' newline ...
        'soc = max(0.05, min(0.99, soc));' newline ...
        '' newline ...
        '% Current' newline ...
        'if charging' newline ...
        '    current = 5.0 + 0.3 * sin(t * 0.5);' newline ...
        'else' newline ...
        '    current = -3.5 + 0.3 * sin(t * 0.5);' newline ...
        'end' newline ...
        '' newline ...
        '% Voltage' newline ...
        'vCell = 3.0 + 1.0 * soc + 0.1 * sin(t * 0.2);' newline ...
        'voltage = vCell * NUM_CELLS;' newline ...
        '' newline ...
        '% Temperature (Celsius)' newline ...
        'temp_c = 25 + abs(current) * 0.8 + 2 * sin(t * 0.1);' newline ...
        'tempK = temp_c + 273;' newline ...
        '' newline ...
        '% Per-cell variations' newline ...
        'vPar = zeros(1, NUM_CELLS);' newline ...
        'socPar = zeros(1, NUM_CELLS);' newline ...
        'for i = 1:NUM_CELLS' newline ...
        '    phase = (i-1) * 0.7 + t * 0.3;' newline ...
        '    vPar(i) = vCell + 0.02 * sin(phase);' newline ...
        '    socPar(i) = soc + 0.01 * sin(phase + 1.0);' newline ...
        'end' newline ...
        '' newline ...
        '% Pack and send UDP (27 doubles = 216 bytes)' newline ...
        'packet = [current, cyc, soc, socPar, tempK, voltage, vPar];' newline ...
        'byteData = typecast(packet, ''uint8'');' newline ...
        '' newline ...
        'import java.net.DatagramPacket' newline ...
        'dp = DatagramPacket(byteData, length(byteData), udpAddr, UDP_PORT);' newline ...
        'udpSocket.send(dp);' newline ...
        '' newline ...
        '% Outputs for display' newline ...
        'soc_pct = soc * 100;' newline ...
        'cycles = cyc;' newline ...
    ];
end
